# Generated by Django 5.2.7 on 2025-11-02 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_teacher_person_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'AddressDB',
            },
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'TeacherDB'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(default='Teacher', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='addresss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.city'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.city')),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.teacher')),
            ],
            options={
                'verbose_name_plural': 'StudentDB',
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
