# Generated by Django 5.2.7 on 2025-11-02 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_city_alter_teacher_options_alter_teacher_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='person.teacher'),
        ),
    ]
