# Generated by Django 5.2.7 on 2025-11-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_alter_student_class_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='addresss',
            new_name='address',
        ),
    ]
